services:

  vote:
    image: myriamaker/voting-app-vote:latest
    ports:
      - "8080:8080"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - frontend
      - backend

  result:
    image: myriamaker/voting-app-result:latest
    ports:
      - "8081:8081"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - frontend
      - backend

  worker:
    image: myriamaker/voting-app-worker:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - backend

  redis:
    image: redis:7-alpine
    networks:
      - backend

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  db-data:

networks:
  frontend:
    driver: overlay
  backend:
    driver: overlay